name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dump-toolchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup-ubuntu.sh

      - name: Dump dependencies
        run: .github/workflows/dump.sh

  build-toolchain:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup-ubuntu.sh

      - name: Cache Toolchain (${{matrix.toolchain}})
        uses: actions/cache@v2
        env:
          cache-name: cached-cross-compiler
        with:
          path: |
            **/build/toolchain/${{matrix.toolchain}}/local
          key: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('build/toolchain/{0}/build.sh', matrix.toolchain)) }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('build/toolchain/{0}/build.sh', matrix.toolchain)) }}

      - name: Build Toolchain
        run: |
          build/toolchain/${{matrix.toolchain}}/build.sh x86_64

  build-system:
    needs: build-toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup-ubuntu.sh

      - name: Cache Toolchain (${{matrix.toolchain}})
        uses: actions/cache@v2
        env:
          cache-name: cached-cross-compiler
        with:
          path: |
            **/build/toolchain/${{matrix.toolchain}}/local
          key: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('build/toolchain/{0}/build.sh', matrix.toolchain)) }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('build/toolchain/{0}/build.sh', matrix.toolchain)) }}

      - name: Build System
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} all

  build-loader:
    needs: build-toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup-ubuntu.sh

      - name: Build Loader
        run: |
          make loader

  build-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup-ubuntu.sh

      - name: Run Tests
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} run-test

  build-bid:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup-ubuntu.sh

      - name: Run BID
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} run-bid
