name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  dump-toolchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup.sh

      - name: Dump dependencies
        run: .github/workflows/dump.sh

  build-toolchain:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup.sh

      - name: Cache Toolchain (${{matrix.toolchain}})
        uses: actions/cache@v2
        env:
          cache-name: cached-cross-compiler
        with:
          path: |
            **/meta/toolchain/${{matrix.toolchain}}/local
          key: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('meta/toolchain/{0}/build.sh', matrix.toolchain)) }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('meta/toolchain/{0}/build.sh', matrix.toolchain)) }}

      - name: Build Toolchain
        run: |
          meta/toolchain/${{matrix.toolchain}}/build.sh

  build-system:
    needs: build-toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup.sh

      - name: Cache Toolchain (${{matrix.toolchain}})
        uses: actions/cache@v2
        env:
          cache-name: cached-cross-compiler
        with:
          path: |
            **/meta/toolchain/${{matrix.toolchain}}/local
          key: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('meta/toolchain/{0}/build.sh', matrix.toolchain)) }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.toolchain}}-${{hashFiles(format('meta/toolchain/{0}/build.sh', matrix.toolchain)) }}

      - name: Build System
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} all

  build-loader:
    needs: build-toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup.sh

      - name: Build Loader
        run: |
          make loader

  build-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup.sh

      - name: Run Tests
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} run-test

  build-bid:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gnu, llvm]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: .github/workflows/setup.sh

      - name: Run BID
        run: |
          make CONFIG_TOOLCHAIN=${{matrix.toolchain}} run-bid

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: .github/workflows/setup.sh

    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        exclude: './thirdparty ./sources/libs/proto ./sources/utils/test.c'
        clangFormatVersion: 12
